# Put custom.scm right after directory
format = "$directory${custom.scm}$all"

[buf]
disabled = true

[character]
error_symbol = "[󰘧](bold red)"
success_symbol = "[󰘧](bold green)"

[directory]
truncate_to_repo = false

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
disabled = true
symbol = " "
truncation_length = 18

[git_status]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[custom.scm]
command = "jj-starship --strip-bookmark-prefix 'dmmulroy/' --truncate-name 20 --bookmarks-display-limit 1"
when = "jj-starship detect"
shell = ["sh"]
format = "$output "

[golang]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[package]
disabled = true

